### PR TITLE
added notification ability fixes #9

### LINKED ISSUE #9: Send notification
I am using Incus https://github.com/Imgur/incus and trying to send a notification, so far everything works except the notification itself, meaning the phone recieves the message and the data but does not show a notification.
I was looking at https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages and https://github.com/alexjlockwood/gcm/blob/master/message.go#L7-L15 and is it possibe it is not at all possible to do this atm? Or am I missing something.

cc @jacobgreenleaf (dev for Incus)

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
fixes #9 according to https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages

I added the option at the end to make it non breaking (I hope, never done Go before ^^) 
Let me know if this needs any changing otherwise would it be possible to merge since we need it asap.

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Hate to bump this but any eta on this or comments? 

cc @alexjlockwood

**Comment by codepushr** [comment]
@AdriVanHoudt Can you add `content_available` and `priority`? See #12 - I think your PR is already more advanced.

**Comment by AdriVanHoudt** [comment]
I can look into it, `content_available` is ios specific right?

**Comment by codepushr** [comment]
Yes! It's needed to wake up an iOS app if a notification arrives.

**Comment by AdriVanHoudt** [comment]
I can only do this by end of the week btw, just a heads up ;)

**Comment by codepushr** [comment]
That's absolutely fine :)

**Comment by pauldub** [comment]
Hello, it would be nice to see this being merged. It is simple enough that it should not be an issue @alexjlockwood  would your like a PR with `Notification` being pointer or anything else? I think it would provide a better API that way.

**Comment by AdriVanHoudt** [comment]
@pauldub wow completely lost track of this, will add this back on my todo list!

**Pull request closed without merging**
